const paths={folder:'M2 5h7l2 2h11v14H2z',file:'M6 2h9l5 5v15H6z M14 2v6h6',WordFile:'M6 2h9l5 5v15H6z M14 2v6h6 M9 12h8 M9 16h8',ImageFile:'M3 3h18v18H3z M3 17l6-6 4 4 3-3 5 6 M15 7h.01',undo:'M3 10a9 9 0 1 1 2 9 M3 3v7h7',redo:'M21 10a9 9 0 1 0-2 9 M21 3v7h-7',copy:'M8 7h12v15H8z M4 17V2h11v5',paste:'M8 4H4v18h16V4h-4 M8 2h8v5H8z M8 11h8 M8 15h8',delete:'M3 6h18 M9 6V3h6v3 M6 6l1 16h10l1-16 M10 10v8 M14 10v8',list:'M3 4h3v3H3z M10 5h11 M3 11h3v3H3z M10 12h11 M3 18h3v3H3z M10 19h11',tag:'M3 3h8l10 10-8 8L3 11z M7 7h.01',person:'M8 6a4 4 0 1 0 8 0a4 4 0 1 0-8 0 M4 22v-6q8-7 16 0v6',pulse:'M1 12h5l3-9 5 18 3-9h6',calculator:'M5 2h14v20H5z M8 5h8v4H8z M8 13h1 M12 13h1 M16 13h1 M8 17h1 M12 17h1 M16 17h1',search:'M15 15l7 7 M2 9a7 7 0 1 0 14 0a7 7 0 1 0-14 0'};
function icon(name){const el=document.createElementNS('http://www.w3.org/2000/svg','svg');el.setAttribute('viewBox','0 0 24 24');el.setAttribute('aria-hidden','true');const p=document.createElementNS(el.namespaceURI,'path');p.setAttribute('d',paths[name]||paths.file);el.append(p);return el}
for(const [id,key] of Object.entries({'undo':'undo','redo':'redo','list-icon':'list','tag-icon':'tag','folder-heading':'folder','visitor-heading':'person','pulse':'pulse','calculator':'calculator','xml-icon':'file','search-icon':'search'}))document.getElementById(id).prepend(icon(key));
for(const id of ['copy','paste','delete'])document.getElementById(id).prepend(icon(id));
let state,busy=false;
function renderProgress(p){document.getElementById('current').textContent=p.name;const idle=p.status==='idle';document.getElementById('percent').textContent=idle?'idle':Math.floor(100*p.visited/p.total)+'%';document.getElementById('progress').value=idle?0:100*p.visited/p.total;document.getElementById('node-count').textContent=idle?'尚未執行':`${p.visited} / ${p.total} Nodes`}
function render(s){state=s;const tree=document.getElementById('tree');tree.replaceChildren();for(const row of s.rows){const el=document.createElement('div');el.className='row'+(row.directory?' directory':'')+(row.searchMatch?' search-match':'')+(row.id===s.selected?' selected':'');el.setAttribute('role','treeitem');el.setAttribute('aria-level',row.depth+1);el.setAttribute('aria-selected',row.id===s.selected);el.tabIndex=0;el.dataset.id=row.id;el.style.marginLeft=row.depth*25+'px';for(let i=0;i<row.depth;i++){const line=document.createElement('span');line.className='branch-line';line.style.left=(-15-i*25)+'px';el.append(line)}const symbol=document.createElement('span');symbol.className='node-icon';symbol.append(icon(row.directory?'folder':row.kind));const label=document.createElement('span');label.className='label';label.textContent=row.name;const meta=document.createElement('span');meta.className='meta';meta.textContent=`(${row.details})`;label.append(meta);const tags=document.createElement('span');tags.className='tags';for(const tag of row.tags){const badge=document.createElement('span');badge.className='badge '+tag;badge.append(document.createTextNode(tag.toUpperCase()));const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label',`移除 ${row.name} 的 ${tag}`);remove.onclick=e=>{e.stopPropagation();action({action:'removeTag',id:row.id,tag})};badge.append(remove);tags.append(badge)}el.append(symbol,label,tags);el.onclick=()=>action({action:'select',id:row.id});el.onkeydown=e=>{if(e.target===el&&(e.key==='Enter'||e.key===' ')){e.preventDefault();el.click()}};tree.append(el)}
for(const b of document.querySelectorAll('[data-sort]')){const active=b.dataset.sort===s.criterion;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);b.textContent=({Name:'名稱',Size:'大小',Extension:'類型',Tag:'標籤'})[b.dataset.sort]+(active?(s.direction==='Asc'?' ↑':' ↓'):'')}
for(const b of document.querySelectorAll('[data-tag]')){const count=s.counts[b.dataset.tag];b.querySelector('.count').textContent=count;b.querySelector('.count').hidden=count===0}
renderLogs(s.logs,s.searchSummary);renderProgress(s.progress);controls();}
function logElement(log){const el=document.createElement('div');el.className='entry '+log.kind;el.textContent=['Trace','Match','SearchSummary'].includes(log.kind)?log.text:`[${log.kind}] ${log.text}`;if(log.path)el.title=log.path;return el}
function renderLogs(logs,summary){const box=document.getElementById('logs');box.replaceChildren();for(const log of [...logs].reverse()){if(log.kind!=='SearchSummary')box.append(logElement(log))}if(summary)box.append(logElement({kind:'SearchSummary',text:summary}))}
function streamEvent(item){if(item.type==='searchReset'){document.querySelectorAll('.search-match').forEach(x=>x.classList.remove('search-match'));document.querySelectorAll('.SearchSummary').forEach(x=>x.remove())}if(item.type==='match'){const row=[...document.querySelectorAll('.row')].find(x=>x.dataset.id===item.nodeId);if(row)row.classList.add('search-match')}if(item.type==='log'){const box=document.getElementById('logs');if(item.entry.kind==='SearchSummary')box.append(logElement(item.entry));else box.prepend(logElement(item.entry))}}
function controls(){document.querySelectorAll('button,input').forEach(b=>b.disabled=busy);if(!state)return;document.getElementById('undo').disabled=busy||!state.undoCount;document.getElementById('redo').disabled=busy||!state.redoCount;document.getElementById('paste').disabled=busy||!state.canPaste;document.getElementById('delete').disabled=busy||!state.canDelete}
async function action(payload){if(busy)return;busy=true;controls();try{const response=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw Error('HTTP '+response.status);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let index;while((index=buffer.indexOf('\n'))>=0){const text=buffer.slice(0,index);buffer=buffer.slice(index+1);if(!text)continue;const item=JSON.parse(text);streamEvent(item);if(item.type==='progress')renderProgress(item.progress);if(item.state)render(item.state);if(item.download){const url=URL.createObjectURL(new Blob([item.download.content],{type:'application/xml;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=item.download.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}if(done)break}}catch(error){const el=document.createElement('div');el.className='entry Error';el.textContent='[Error] '+error.message;document.getElementById('logs').prepend(el)}finally{busy=false;controls()}}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action({action:b.dataset.action}));document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>action({action:'sort',criterion:b.dataset.sort}));document.querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>action({action:'addTag',tag:b.dataset.tag}));document.getElementById('search-form').onsubmit=e=>{e.preventDefault();action({action:'search',extension:document.getElementById('extension').value})};fetch('/api/state').then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(render).catch(e=>document.getElementById('logs').textContent='[Error] '+e.message);
